# If you want to print yaml blocks(helm.yaml file in components) anywhere in  kuberenets manifest file in the helm charts we use a function called "toYaml"

{{- if .Values.configMap.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appName }}
data:
{{ - with .Values.configMap.data }}
  {{ - toYaml . | nindent 2 }}
{{ - end }}
{{- end -}}
