#A basic manifest for creating a Kubernetes deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}

spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
        - name: {{ .Values.image }}
          image: 124374336606.dkr.ecr.us-east-1.amazonaws.com/{{ .Values.image }}
