{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta2
kind: ExternalSecret
metadata:
  name: {{ .Values.appName }}
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: roboshop
    kind: ClusterSecretStore
  target:
    name: {{ .Values.appName }}
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: roboshop/all
{{- end -}}
