apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.appName }}
  ports:
    - protocol: TCP
      port: 8080
      targetPort: {{ .Values.service.targetPort }}